plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.google.ksp)
    alias(libs.plugins.hilt.android)
}

android {
    namespace 'com.unfair.moment'

    defaultConfig {
        minSdk 26

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = libs.versions.jdkRelease.get()
        targetCompatibility = libs.versions.jdkRelease.get()
    }
    buildFeatures {
        compose true
    }
}

dependencies {
    implementation libs.hilt.android
    implementation libs.androidx.hilt.navigation.compose
    ksp libs.hilt.compiler
    implementation libs.androidx.core.ktx
    implementation libs.androidx.lifecycle.common
    implementation libs.androidx.lifecycle.viewmodel.compose
    implementation libs.androidx.activity.compose
    implementation libs.androidx.navigation.compose
    implementation platform(libs.compose.bom)
    implementation libs.compose.ui
    implementation libs.compose.ui.tooling.preview
    implementation libs.compose.material3
    implementation libs.compose.material.icons
    implementation libs.compose.foundation
    implementation libs.bundles.room
    ksp libs.room.compiler
    debugImplementation libs.compose.ui.tooling
    debugImplementation libs.compose.ui.tooling.preview
}
